[tool.poetry]
name = "chess-cli"
version = "0.1.0"
description = "A repl to edit and analyse chess games."
authors = ["Tage Johansson <tajo9185@uu.student.se>"]
license = "GPL-3.0-or-later"

[tool.poetry.scripts]
chess-cli = 'chess_cli:run'

[tool.poetry.dependencies]
python = "^3.11"
cmd2 = "^2.4"
chess = "^1.9"
appdirs = "^1.4.4"
toml = "^0.10.2"
more-itertools = "^8.14"
psutil = "^5.9.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^1.3"
nuitka = "^1.6.6"
types-psutil = "^5.9.5.15"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
fast = true
preview = true
src = "chess_cli/"
