[tool.poetry]
name = "chess-cli"
version = "0.1.0"
description = "A repl to edit and analyse chess games."
authors = ["Tage Johansson <tajo9185@uu.student.se>"]
license = "GPL-3.0-or-later"

[tool.poetry.scripts]
chess-cli = 'chess_cli:run'

[tool.poetry.dependencies]
python = "^3.9"
cmd2 = "^2.1.1"
chess = "^1.6.1"
appdirs = "^1.4.4"
dhall = "^0.1.7"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
